//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Season_tickets = new HashSet<Season_tickets>();
        }
    
        public int Id { get; set; }
        public string last_name { get; set; }
        public string name { get; set; }
        public string fathers_name { get; set; }
        public string adres { get; set; }
        public string recomendation { get; set; }
        public string phone { get; set; }
        public Nullable<int> age { get; set; }
        public string pol { get; set; }
    
        public virtual ICollection<Season_tickets> Season_tickets { get; set; }
    }
}
