//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season_tickets
    {
        public Season_tickets()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int Id { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_ticket_type { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string freeze_status { get; set; }
        public Nullable<int> id_trainer { get; set; }
        public string inOut { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Types_season_tickets Types_season_tickets { get; set; }
        public virtual Trainers Trainers { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
