//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types_season_tickets
    {
        public Types_season_tickets()
        {
            this.Season_tickets = new HashSet<Season_tickets>();
        }
    
        public int Id { get; set; }
        public string type { get; set; }
        public string age_group { get; set; }
        public string time_type { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ICollection<Season_tickets> Season_tickets { get; set; }
    }
}
