//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ermakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int Id { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public string inOutType { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Season_tickets Season_tickets { get; set; }
    }
}
